# Generated by Django 4.2.5 on 2023-09-13 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('pacienteNome', models.CharField(blank=True, max_length=100, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=8, null=True)),
                ('cpfOrRg', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('acompanhanteNome', models.CharField(blank=True, max_length=100, null=True)),
                ('acompanhanteIdade', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('localOcorrencia', models.CharField(max_length=100)),
                ('publicadoEm', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipe', models.CharField(max_length=100)),
                ('criadoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
