# Generated by Django 4.2.5 on 2023-11-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnesegestacional',
            old_name='pressao_na_regiao_ou_vonatde_de_evacuar',
            new_name='pressao_na_regiao_ou_vontade_de_evacuar',
        ),
    ]
