# Generated by Django 4.2.5 on 2023-09-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencias',
            name='sexo',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
