# Generated by Django 4.2.5 on 2023-11-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_pressao_na_regiao_ou_vonatde_de_evacuar_anamnesegestacional_pressao_na_regiao_ou_vontade_de_e'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnesegestacional',
            old_name='Existe_probabilidade_de_complicacoes',
            new_name='existe_probabilidade_de_complicacoes',
        ),
    ]
