# Generated by Django 4.2.6 on 2023-12-01 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_existe_probabilidade_de_complicacoes_anamnesegestacional_existe_probabilidade_de_complicacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciatipo',
            name='outro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatipo',
            name='queda_altura',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrenciatipo',
            name='registroId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registropaciente'),
        ),
        migrations.CreateModel(
            name='registrarocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('acompanhante', models.BooleanField(default=False)),
                ('local_da_ocorrencia', models.CharField(max_length=100)),
                ('m', models.CharField(max_length=100)),
                ('s1', models.CharField(max_length=100)),
                ('s2', models.CharField(max_length=100)),
                ('s3', models.CharField(max_length=100)),
                ('demandante', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=100)),
                ('registroId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registropaciente')),
            ],
        ),
    ]
