# Generated by Django 4.2.6 on 2023-12-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ocorrenciatipo_outro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciatipo',
            name='queda_altura',
            field=models.BooleanField(default=False),
        ),
    ]
