# Generated by Django 4.2.6 on 2023-12-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_problemasencontrados_outro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemasencontrados',
            name='registroId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registropaciente'),
        ),
    ]
